### ISSUE TITLE
installs chromium (120MB)

### ISSUE THREAD

**Issue by kpennell** [rocketspacer/jsonresume-theme-rocketspacer#2]
Any ideas why this would install chromium?

![image](https://user-images.githubusercontent.com/1060385/70813644-1c15a000-1dca-11ea-8f5c-b9f1df9c7e37.png)

**Comment by rocketspacer** [comment]
@kpennell This is a dependency of `resume-cli` I think it uses chromium to provide the html to pdf feature.
