### ISSUE TITLE
resume-cli dep

### ISSUE THREAD

**Issue by thomasdavis** [rocketspacer/jsonresume-theme-rocketspacer#3]
The resume-cli dependency is too large for the theme server, can you move it to devDeps and republish to npm?

**Comment by rocketspacer** [comment]
@thomasdavis Done

**Comment by rocketspacer** [comment]
@thomasdavis can you allow extra custom fields inside `resume.json`?

**Comment by thomasdavis** [comment]
Thanks, I'm just reuploading your theme to the official registry. 

The schema allows you to have any extra fields you would like in the `meta` property, themes can tell users to put values there if they need. 

We do have `certificates` coming into the official schema but not sure how long until we release sorry.
